### ISSUE TITLE
POST mappings failed when we try to create a subdomain (fresh install)

### ISSUE THREAD

**Issue by Wolfy64** [garageScript/myProxy#210] opened 2019-09-24 07:48 UTC
**On master branch**

Create a subdomain give me this error:

```
(node:16717) UnhandledPromiseRejectionWarning: Error: Command failed: id -u git
id: git: no such user

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:209:13)
    at Pipe.<anonymous> (net.js:658:12)
(node:16717) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16717) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by songz** [comment] 2019-09-24 15:16
need to debug this. `git` user is supposed to get created during the setup step.

**Comment by songz** [comment] 2019-10-11 17:10
closing, cannot reproduce.

**Closed by songz** 2019-10-11 17:10 UTC
Labels: Bug 🐛
